### ISSUE TITLE
Method to unload instance

### ISSUE THREAD

**Issue by pommedeterresautee** [vinhkhuc/JFastText#1]
It seems there is no method to unload a model to free memory.
Can you please add one or give instruction on how to implement it?

Kind regards,
Michael

**Comment by vinhkhuc** [comment]
Hi Michael,
It turns out that Java's GC doesn't collect memory allocated by native calls. I've added unloadModel() to release memory.

Let me know if it works for you.

Thanks,
Vinh

**Comment by pommedeterresautee** [comment]
Thanks, that's exactly what I was looking for. 
I try it tonight!

Kind regards,
Michaël

**Comment by pommedeterresautee** [comment]
Thanks it words!

**Comment by pommedeterresautee** [comment]
Would it be possible to update maven? 

https://search.maven.org/#artifactdetails%7Ccom.github.vinhkhuc%7Cjfasttext%7C0.1%7Cjar

**Comment by vinhkhuc** [comment]
Hi Michaël,
I've deployed v0.2 to maven central.

Thanks,
Vinh
