### ISSUE TITLE
Cannot rebuilt jfasttext wrapper with Fasttext version 0.1.0

### ISSUE THREAD

**Issue by villahp** [vinhkhuc/JFastText#37]
Due to update structure of many class like dictionary in Fasttext library, I cannot rebuilt with version 0.1.0. Is there any one could help me update fasttext wrapper? 
Thanks for your help!

Here is log when I rebuilt jfasttext wrapper with fasttext version 0.1.0: 

``In file included from /mnt/cuongpx/workspace/toolkits/jfasttext-custom/JFastText-master/src/main/java/../cpp/fasttext_wrapper_javacpp.h:13:0,
                 from /mnt/cuongpx/workspace/toolkits/jfasttext-custom/JFastText-master/target/classes/com/github/jfasttext/jniFastTextWrapper.cpp:102:
/mnt/cuongpx/workspace/toolkits/jfasttext-custom/JFastText-master/src/main/java/../cpp/fasttext_wrapper.cc:91:61: error: ‘class fasttext::Vector’ has no member named ‘m_’
         return std::vector<real>(vec.data_, vec.data_ + vec.m_);``
                                                             ^

**Comment by spomerville** [comment]
I was able to build it with the `v0.1.0` tag, but the latest code on master does break with this error above. Just throwing it out there if you do a `git checkout v0.1.0` on the cpp fastText repo and rebuild this wrapper it should work.

**Comment by villahp** [comment]
Thank you, I have rebuilt with fasttext v0.1.0 successful.
