### ISSUE TITLE
JFasttext throws exception during loading model

### ISSUE THREAD

**Issue by sonerx** [vinhkhuc/JFastText#5]
When I try to load a fastext model, following exception is thrown:

java.lang.RuntimeException: vector
	at com.github.jfasttext.FastTextWrapper$FastTextApi.loadModel(Native Method)
	at com.github.jfasttext.JFastText.loadModel(JFastText.java:25)

I try to load a model which is generated with the latest fasttext as today

**Comment by vinhkhuc** [comment]
Hi sonerx,
I've upgraded jfasttext to v0.3 with the latest fasttext. Can you try it to see if it resolves your issue?

**Comment by sonerx** [comment]
Hi vinhkhuc,

Thansk for the fix. When I run my code with the version 0.3 Java crash down and generates attached log.
[hs_err_pid2174.log.txt](https://github.com/vinhkhuc/JFastText/files/1000435/hs_err_pid2174.log.txt)

**Comment by vinhkhuc** [comment]
Glad that it works. 
Thanks for the suggestion. I will make the library more robust in the next releases.
