### ISSUE TITLE
Statically linked fasttext

### ISSUE THREAD

**Issue by ELind77** [vinhkhuc/JFastText#6]
Hi,

I'm trying to deploy to a system that doesn't support c++11 and I'd like to statically compile the c libs in jfasttext.  I can get fasttext to compile fine with the -static flag for gcc but when I add that flag to the maven file is gets overridden by some default options somewhere.  Can you help me get this to compile a statically linked fasttext with JNI bindings?

Eric

**Comment by vinhkhuc** [comment]
Hi Eric,
I've tried to compile fasttext with static linking. Just wonder if you try to update pom.xml as follows:

```
<compilerOptions>
    <compilerOption>-std=c++0x</compilerOption>
    <compilerOption>-static</compilerOption>
    <compilerOption>-I${project.build.sourceDirectory}/../cpp</compilerOption>
</compilerOptions>
```
i.e. adding the new compiling option "-static"

**Comment by vinhkhuc** [comment]
I'm closing this one. Feel free to reopen it.
